[package]
name = "playing-cards"
version = "0.1.0"
authors = ["Matt Hooper <matthewjhooper94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
